language: node_js
node_js:
  - 10.15.1
cache:
  directories:
    - node_modules
before_install:
  # change directory to the api directory
  - "cd api"
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage